name: Bump Formula

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Bump Formula
        uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: ssh-import-id
          homebrew-tap: jitinnair1/ssh-import-id
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
